CREATE TABLE IF NOT EXISTS Prod (
    P_ID VARCHAR(255) NOT NULL,
    P_Name VARCHAR(255) NOT NULL,
    PRIMARY KEY (P_ID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Supp (
    S_ID VARCHAR(255) NOT NULL,
    S_Name VARCHAR(255) NOT NULL,
    PRIMARY KEY (S_ID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ProdSupp (
    P_ID VARCHAR(255) NOT NULL,
    S_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (P_ID, S_ID),
	FOREIGN KEY (P_ID) REFERENCES Prod(P_ID),
	FOREIGN KEY (S_ID) REFERENCES Supp(S_ID)
)  ENGINE=INNODB;

INSERT INTO Prod (P_ID, P_Name) VALUES ('P1', 'Carrot');
INSERT INTO Prod (P_ID, P_Name) VALUES ('P2', 'Potatoe');
INSERT INTO Prod (P_ID, P_Name) VALUES ('P3', 'Onion');

INSERT INTO Supp (S_ID, S_Name) VALUES ('S1', 'Supp_North');
INSERT INTO Supp (S_ID, S_Name) VALUES ('S2', 'Supp_South');

INSERT INTO ProdSupp (P_ID, S_ID) VALUES ('P1', 'S1');
INSERT INTO ProdSupp (P_ID, S_ID) VALUES ('P1', 'S2');
INSERT INTO ProdSupp (P_ID, S_ID) VALUES ('P3', 'S2');
INSERT INTO ProdSupp (P_ID, S_ID) VALUES ('P2', 'S1');
INSERT INTO ProdSupp (P_ID, S_ID) VALUES ('P2', 'S2');
